<?php
/**
 * @copyright	Copyright (C) 2005 - 2011 Joomlashack / Meritage Assets
 * @author		Jeremy Wilken - Joomlashack
 * @package		Wright
 *
 * Do not edit this file directly. You can copy it and create a new file called
 * 'custom.php' in the same folder, and it will override this file. That way
 * if you update the template ever, your changes will not be lost.
 */
// no direct access
defined('_JEXEC') or die('Restricted access');
?>
<doctype>
<html>
<head>
<w:head />
<link href='http://fonts.googleapis.com/css?family=Droid+Sans&v1' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Droid+Serif&v1' rel='stylesheet' type='text/css'>
<?php if(($this->countModules('banner') == 0)) { ?>
<style type="text/css">
body.home #wrapper-inner {
background: url("templates/js_breeze/images/innerfade_content.png") no-repeat scroll center top transparent;
}
</style>
<?php } ?>
</head>
<body>
<div id="wrapper">
  <div id="header" class="container_12 clearfix">
    <w:logo name="menu" />
    <div class="clear"></div>
  </div>
  <div class="clear"></div>
  <div id="wrapper-inner">
    <div id="banner" class="container_12 clearfix">
      <w:module type="single" name="banner" chrome="none" />
      <div class="clear"></div>
    </div>
    <div class="clear"></div>
    <div id="container">
      <div id="container-inner" class="border">
        <div class="inner-border">
          <div class="container_12 clearfix">
          	<?php if ($this->countModules('grid-top1')) : ?>
            <div id="stage">
            	<w:module type="grid" name="grid-top1" chrome="wrightflexgrid" />	
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <?php endif; ?>
            <section id="main">
              <?php if ($this->countModules('breadcrumb')) : ?>
              <div id="pathway" class="border">
                <div id="pathway-inner" class="inner-border">
                  <w:module type="single" name="breadcrumb" chrome="none" />
                  <div class="clear"></div>
                </div>
              </div>
              <div class="clear"></div>
              <?php endif; ?>
              <w:content />
            </section>
            <aside id="sidebar1">
              <w:module name="sidebar1" chrome="xhtml" />
            </aside>
            <aside id="sidebar2">
              <w:module name="sidebar2" chrome="xhtml" />
            </aside>
            <div class="clear"></div>
            <?php if ($this->countModules('grid-bottom1')) : ?>
            <div id="elements">
            	<w:module type="grid" name="grid-bottom1" chrome="wrightflexgrid" />	
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <?php endif; ?>
          </div>
        </div>
      </div>
    </div>
    <?php if ($this->countModules('grid-bottom2')) : ?>
    <div id="bottom">
      <div id="bottom-inner" class="border">
        <div class="inner-border">
          <div class="container_12 clearfix">
            <w:module type="grid" name="grid-bottom2" chrome="wrightflexgrid" />
            <div class="clear"></div>
          </div>
        </div>
      </div>
    </div>
    <?php endif; ?>
  </div>
</div>
<div id="footer">
  <div id="footer-inner">
    <div class="container_12">
      <w:module type="single" name="bottommenu" chrome="none" />
      <w:module type="single" name="footer" chrome="none" />
      <w:footer />
      <div class="clear"></div>
    </div>
  </div>
</div>
<w:module type="single" name="debug" chrome="xhtml" />
<?php //echo $this->document->params->get("footerscript",""); ?>
</body>
</html>
